
UI_MF_TAB_1 = "首页"
UI_MF_TAB_2 = "插画"
UI_MF_TAB_3 = "资产"
UI_TEXT_DESCRIPTION = "描述"
UI_TEXT_DOWNLOAD = "下载"
UI_TEXT_DRAG_AND_DROP = "移除图片"
UI_TEXT_FRIENDS_ONLY = "私人"
UI_TEXT_HIDDEN = "隐藏"
UI_TEXT_ORIGINAL_SIZE = "原尺寸"
UI_TEXT_PUBLIC = "公开"
UI_TEXT_SUBSCRIBE = "订阅"
UI_TEXT_SUBSCRIBED = "已订阅"
UI_TEXT_TAGS = "标签"
UI_TEXT_UNSUBSCRIBE = "解除订阅"

DEFAULT_TEXT_ALL_ASSET = "所有资产"
DEFAULT_TEXT_ITEM = "物品"
DEFAULT_TEXT_NEW_ASSET = "新资产"
DEFAULT_TEXT_NEW_FILE = "新文件"
DEFAULT_TEXT_SCENE = "场景"

CTX_MENU_ADD = "增加"
CTX_MENU_COPY = "复制"
CTX_MENU_CUT = "剪切"
CTX_MENU_DEFAULT_SCENE = "默认场景"
CTX_MENU_DELETE = "删除"
CTX_MENU_DUPLICATE = "副本"
CTX_MENU_EDIT = "编辑"
CTX_MENU_PASTE ="粘贴"

DLG_TITLE_ASSET_INFO = "资产信息"
DLG_TITLE_ASSET_LIMITATION = "注意"
DLG_TITLE_ASSET_MANAGER = "资产管理"
DLG_TITLE_CREATE_ITEMS = "创建物品"
DLG_TITLE_DEFAULT_SCENE = "默认场景设置"
DLG_TITLE_DELETE_SCENE = "删除场景"
DLG_TITLE_DUPLICATE_DIRECTORY_NAME = "目录名称重复"
DLG_TITLE_EXPORT_ASSET = "导出资产文件"
DLG_TITLE_EXPORT_IMAGES = "导出图片"
DLG_TITLE_GENERAL_SETTINGS = "设置"
DLG_TITLE_IMPORT_SETTINGS = "导入设置"
DLG_TITLE_ITEM_NAME_ERROR = "物品名称错误"
DLG_TITLE_ITEM_MAX_LIMIT = "最大项目数限制"
DLG_TITLE_ITEM_SETTINGS = "物品设置"
DLG_TITLE_NEW_PROJECT = "新项目"
DLG_TITLE_OLD_IMP = "警告"
DLG_TITLE_OPEN_IMAGE = "打开图片"
DLG_TITLE_OPEN_PROJECT = "打开项目文件"
DLG_TITLE_OVERWRITE_FILE = "覆盖"
DLG_TITLE_PSD_IMPORT = "导入PSD "
DLG_TITLE_SELL_ASSET = "在Steam销售资产"
DLG_TITLE_TUTORIAL = "教程"
DLG_TITLE_UNSUPPORTED_IMG = "不支持的图片格式"
DLG_TITLE_UPLOAD_ASSET = 发布到Steam Workshop"

DLG_BTN_OK = "是"
DLG_BTN_CANCEL = "否"
DLG_BTN_YES = "是"
DLG_BTN_NO = "否"
DLG_BTN_CLOSE = "关闭"
DLG_BTN_EXPORT = "导出"
DLG_BTN_IMPORT = "导入"
DLG_BTN_UPLOAD = "上传"

DLG_LABEL_ASSET_LIMITATION1A = "状态: 限制 "
DLG_LABEL_ASSET_LIMITATION1B = " 资产"
DLG_LABEL_ASSET_LIMITATION2 = "DLC: Unlimited number of assets"
DLG_LABEL_ASSET_TITLE = "资产标题:"
DLG_LABEL_AUTHOR_NAME = "作者名称:"
DLG_LABEL_DESCRIPTION = "描述:"
DLG_LABEL_DIRECTORY = "目录:"
DLG_LABEL_FILE_NAME = "文件名:"
DLG_LABEL_FILE_TYPE = "文件类型:"
DLG_LABEL_GROUP_ID = "组 ID:"
DLG_LABEL_ITEM_NAME = "物品名称:"
DLG_LABEL_IMAGE_SIZE = "图像尺寸:"
DLG_LABEL_LANGUAGE = "语言:"
DLG_LABEL_LAYER = "层:"
DLG_LABEL_PREVIEW = "预览图像:"
DLG_LABEL_PROJECT_TITLE = "项目标题:"
DLG_LABEL_RESOLUSION = "解决方案:"
DLG_LABEL_RULES = "使用协议:"
DLG_LABEL_TAG = "标签:"
DLG_LABEL_TUTORIAL_ASSET_ITEM1 = "1: 预装式"
DLG_LABEL_TUTORIAL_ASSET_ITEM2 = "2: 背景"
DLG_LABEL_TUTORIAL_ASSET_ITEM3 = "3: 装饰"
DLG_LABEL_TUTORIAL_HOME_ITEM1 = "1: 预装式"
DLG_LABEL_TUTORIAL_HOME_ITEM2 = "2: 背景"
DLG_LABEL_TUTORIAL_HOME_ITEM3 = "3: 装饰"
DLG_LABEL_TUTORIAL_ILLUSTRATION_ITEM1 = "1: 选择一个资产文件"
DLG_LABEL_TUTORIAL_ILLUSTRATION_ITEM2 = "2: 选择场景"
DLG_LABEL_TUTORIAL_ILLUSTRATION_ITEM3 = "3: 预装式"
DLG_LABEL_TUTORIAL_ILLUSTRATION_ITEM4 = "4: 背景"
DLG_LABEL_TUTORIAL_ILLUSTRATION_ITEM5 = "5: 装饰"
DLG_LABEL_TUTORIAL_TITLE_ASSET = "如何创建资产"
DLG_LABEL_TUTORIAL_TITLE_HOME = "关于首页"
DLG_LABEL_TUTORIAL_TITLE_ILLUSTRATION = "如何创建立绘"
DLG_LABEL_Z_INDEX = "优先级:"

DLG_CBX_MOVABLE = "可移动"
DLG_CBX_PUBLIC = "公共"

DLG_TAB_GRAPHICS = "图像"
DLG_TAB_INTERFACE = "界面"
DLG_TAB_BANNERS = "Banner"
DLG_TAB_MATURE = "成人内容"

DLG_TEXT_AGREEMENT = "使用前，表示你同意以下条款"
DLG_TEXT_ASSET_LIMITATION1 = "这些现象将会在你安装资产时 "
DLG_TEXT_ASSET_LIMITATION2 = " 出现.\n\n"
DLG_TEXT_ASSET_LIMITATION3 = "(Steam版本) 可以安装 "
DLG_TEXT_ASSET_LIMITATION4 = " 资产.\n但需要DLC来解锁更多内容.\n\n如果你想添加更多 "
DLG_TEXT_ASSET_LIMITATION5 = " 资产, 资产中的图像不会被加载.\n请设置加载的资产数目 "
DLG_TEXT_ASSET_LIMITATION6 = " 少一点."
DLG_TEXT_CONFIRM_CLOSE = "是否保存设置?"
DLG_TEXT_DELETE_SCENE = "如果你删除一个场景，那么所有使用这个场景的物品\n都会被删除.是否继续删除?"
DLG_TEXT_DUPLICATE_DIRECTORY_NAME = 目录下有同名文件"
DLG_TEXT_EXPORT_ASSET_DONE = "EGD导出成功."
DLG_TEXT_EXPORT_ASSET_ERROR = "无法导出EGD文件."
DLG_TEXT_ITEM_MAX_LIMIT = "T项目数目超过限制.\n请移除一些物品再重试."
DLG_TEXT_ITEM_NAME_EMPTY = "请输入物品名称."
DLG_TEXT_ITEM_NAME_ERROR = "名称包含非法字符s."
DLG_TEXT_OLD_IMP = "imp适用于过去的版本 (v1.0.3 or earlier).\n如果你读取数据, 可能在在某些版本无法使用,\n包括输出文件数据.继续读取imp文件吗?"
DLG_TEXT_OVERWRITE_ASSET_ERROR = "无法重写被使用的文件"
DLG_TEXT_OVERWRITE_FILE = "文件已经存在，是否覆盖?"
DLG_TEXT_OVERWRITE_FILE_ERROR = "文件被设置为只读.\n请使用其他的文件名."
DLG_TEXT_PSD_IMPORT = "PSD导入成功."
DLG_TEXT_PSD_IMPORT_ERROR = "无法导入PSD.\n\n这个错误表示你使用了Photoshop以外的软件制作了PSD.\n请使用Photoshop制作PSD文件"
DLG_TEXT_SHOW_MATURE_CONTENTS = "在首页显示成人内容"
DLG_TEXT_TUTORIAL_HOME1A = "主界面即是启动的界面 "
DLG_TEXT_TUTORIAL_HOME1B = "."
DLG_TEXT_TUTORIAL_HOME2 = "从这个界面选择相应的资产创建你的立绘图像."
DLG_TEXT_TUTORIAL_HOME3 = "1: 浏览已发布的资产.\n2: 获得你喜欢的资产."
DLG_TEXT_TUTORIAL_ASSET1 = "你可以在这个界面创建自己的资产.\n你发布时可以选择收费或免费.\n*请不要发布侵犯他人版权的内容"
DLG_TEXT_TUTORIAL_ASSET2 = "示例"
DLG_TEXT_TUTORIAL_ILLUSTRATION = "你可以使用安装的资产创建立绘."
DLG_TEXT_UNSUPPORTED_IMG = "不支持的图片格式."

ITEM_NAME_BODY = "身体"
ITEM_NAME_CHEST = "胸部"
ITEM_NAME_CROTCH = "胯部"
ITEM_NAME_BODY_HAIR = "体毛"
ITEM_NAME_EYES = "眼睛"
ITEM_NAME_EYEBROWS = "眉毛"
ITEM_NAME_BANGS = "前发"
ITEM_NAME_HAIR = "后发"
ITEM_NAME_HAIR_OTHERS = "发型"
ITEM_NAME_MOUTH = "嘴"
ITEM_NAME_CHEEK = "脸颊"
ITEM_NAME_WEAR_TOP = "服（上）"
ITEM_NAME_WEAR_BOTTOM = "服（下）"
ITEM_NAME_UNDERWEAR_TOP = "内衣（上）"
ITEM_NAME_UNDERWEAR_BOTTOM = "内衣（下）"
ITEM_NAME_ACCESSORY_HEAD = "头部配件"
ITEM_NAME_ACCESSORY_BODY = "身体配件"
ITEM_NAME_ACCESSORY_HAND = "手部配件"
ITEM_NAME_ACCESSORY_FOOT = "脚部配件"
ITEM_NAME_ACCESSORY_OTHERS = "其他配件"
ITEM_NAME_LIQUID = "液体"
ITEM_NAME_ADDITIONAL = "额外添加"
ITEM_NAME_BACKGROUND = "背景"
ITEM_NAME_EFFECT = "效果"
ITEM_NAME_ILLUSTRATION = "插画"
ITEM_NAME_LINE = "效果线"
ITEM_NAME_LETTER = "绘制文字"
ITEM_NAME_DEFAULT = "物品"
ITEM_NAME_UNSELECTED = "(未选择)"

CATEGORY_BODY = "身体"
CATEGORY_CHEST = "胸部"
CATEGORY_CROTCH = "胯部"
CATEGORY_BODY_HAIR = "体毛"
CATEGORY_EYES = "眼睛"
CATEGORY_EYEBROWS = "眉毛"
CATEGORY_MOUTH = "嘴部"
CATEGORY_CHEEK = "脸颊"
CATEGORY_BANGS = "前发"
CATEGORY_HAIR = "头发"
CATEGORY_HAIR_OTHERS = "其他"
CATEGORY_CLOTHES_TOP = "服（上）"
CATEGORY_CLOTHES_TOP_S = "(上)"
CATEGORY_CLOTHES_BOTTOM = "服（下）"
CATEGORY_CLOTHES_BOTTOM_S = "(下)"
CATEGORY_UNDERWARE_TOP = "内衣（上）"
CATEGORY_UNDERWARE_TOP_S = "(上)"
CATEGORY_UNDERWARE_BOTTOM = "内衣（下）"
CATEGORY_UNDERWARE_BOTTOM_S = "(下)"
CATEGORY_ACCESSORY_HEAD = "配饰(头)"
CATEGORY_ACCESSORY_HEAD_S = "(头)"
CATEGORY_ACCESSORY_BODY = "配饰(身体)"
CATEGORY_ACCESSORY_BODY_S = "(身体)"
CATEGORY_ACCESSORY_HAND = "配饰(手)"
CATEGORY_ACCESSORY_HAND_S = "(手)"
CATEGORY_ACCESSORY_FOOT = "配饰(脚)"
CATEGORY_ACCESSORY_FOOT_S = "(脚)"
CATEGORY_ACCESSORY_OTHERS = "配饰(额外)"
CATEGORY_ACCESSORY_OTHERS_S = "(额外)"
CATEGORY_LIQUID = "液体, 气体"
CATEGORY_ADDITIONAL = "追加物"
CATEGORY_BACKGROUND = "背景"
CATEGORY_EFFECT = "效果"
CATEGORY_ILLUSTRATION = "插图"
CATEGORY_LINE = "效果线"
CATEGORY_LETTER = "绘制文字"

TAG_01_ORIGINAL = "基本"
TAG_01_CGI = "CG"
TAG_01_REAL_LIFE = "写实"
TAG_01_PIXEL_ART = "像素"
TAG_01_PERSON = "人物"
TAG_01_MALE = "男"
TAG_01_FEMALE = "女"
TAG_01_BOYS = "男孩"
TAG_01_GIRLS = "女孩"
TAG_01_BASE = "立绘"
TAG_01_HAIR = "头发"
TAG_01_CLOTHES = "衣物"
TAG_01_ACCESSORY = "配件饰品"
TAG_01_BACKGROUND = "背景"
TAG_01_FOREGROUND = "前景"
TAG_01_ICON = "图标"
TAG_01_LINE = "效果线"
TAG_01_LETTER = "绘制文字"
TAG_01_FRAME = "框架"
TAG_01_EFFECT = "效果"
TAG_01_LIQUID = "液体"
TAG_01_GAS = "气体"
TAG_01_ANIME = "动漫"
TAG_01_CARTOON = "卡通"
TAG_01_GAME = "游戏"
TAG_01_SPORTS = "运动"
TAG_01_MUSIC = "音乐"
TAG_01_POP_IDOL = "流行"
TAG_01_MEMES = "Memes"
TAG_01_FOOD = "食物"
TAG_01_ITEM = "物品"
TAG_01_WEAPON = "武器"

TAG_02_VEHICLE = "交通工具"
TAG_02_BUILDING = "建筑"
TAG_02_FURNITURE = "家具"
TAG_02_MACHINE = "机械"
TAG_02_CREATURE = "生物"
TAG_02_ANIMAL = "动物"
TAG_02_PLANT = "植物"
TAG_02_BUG = "昆虫"
TAG_02_LANDSCAPE = "风景"
TAG_02_NATURE = "自然"
TAG_02_OCEAN = "海洋"
TAG_02_SCI_FI = "科幻"
TAG_02_CYBERPUNK = "朋克"
TAG_02_PRESENT = "现代"
TAG_02_MIDDLE_AGES = "中世纪"
TAG_02_ANCIENT = "古代"
TAG_02_FANTASY = "魔幻"
TAG_02_UNIVERSE = "宇宙"
TAG_02_ABSTRACT = "抽象"
TAG_02_KISEKAE = "着装物品"
